---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "commercial-paper-network"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "The Commercial Paper network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  papernet:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer1.magnetocorp.example.com

    # Required. list of peers from participating orgs
    peers:
      peer1.magnetocorp.example.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer5.digibank.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

#
# list of participating organizations in this network
#
organizations:
  Org1:
    mspid: magnetocorpMSP

    peers:
      - peer1.magnetocorp.example.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - camagnetocorp

    adminPrivateKey:
      path: /home/matthew/github.com/ampretia/fabric-application-examples/infrastructure/two-orgs/commercial-paper-network/crypto-config/peerOrganizations/magnetocorp.example.com/users/Admin@magnetocorp.example.com/msp/keystore/8401e58b739fb67ed6c8b3d4c52256de36a613657618cf614768fef71326504c_sk
    signedCert:
      path: /home/matthew/github.com/ampretia/fabric-application-examples/infrastructure/two-orgs/commercial-paper-network/crypto-config/peerOrganizations/magnetocorp.example.com/users/Admin@magnetocorp.example.com/msp/signcerts/Admin@magnetocorp.example.com-cert.pem


  Org2:
    mspid: digibankMSP
    peers:
      - peer5.digibank.example.com
    certificateAuthorities:
      - cadigibank
    adminPrivateKey:
      path: /home/matthew/github.com/ampretia/fabric-application-examples/infrastructure/two-orgs/commercial-paper-network/crypto-config/peerOrganizations/digibank.example.com/users/Admin@digibank.example.com/msp/keystore/9fbcaac2843325754967677da6e2b716835cecc54610a2fcc60c9b5fcabbb713_sk
    signedCert:
      path: /home/matthew/github.com/ampretia/fabric-application-examples/infrastructure/two-orgs/commercial-paper-network/crypto-config/peerOrganizations/digibank.example.com/users/Admin@digibank.example.com/msp/signcerts/Admin@digibank.example.com-cert.pem


#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer1.magnetocorp.example.com:
    url: grpcs://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer1.magnetocorp.example.com
    tlsCACerts:
      path: /home/matthew/github.com/ampretia/fabric-application-examples/infrastructure/two-orgs/commercial-paper-network/crypto-config/ordererOrganizations/magnetocorp.example.com/orderers/orderer1.magnetocorp.example.com/msp/tlscacerts/tlsca.magnetocorp.example.com-cert.pem

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer1.magnetocorp.example.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051

    grpcOptions:
      ssl-target-name-override: peer1.magnetocorp.example.com
      request-timeout: 120001

    tlsCACerts:
      path: /home/matthew/github.com/ampretia/fabric-application-examples/infrastructure/two-orgs/commercial-paper-network/crypto-config/peerOrganizations/magnetocorp.example.com/peers/peer1.magnetocorp.example.com/msp/tlscacerts/tlsca.magnetocorp.example.com-cert.pem


  peer5.digibank.example.com:
    url: grpcs://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer5.digibank.example.com
      request-timeout: 120001
    tlsCACerts:
      path: /home/matthew/github.com/ampretia/fabric-application-examples/infrastructure/two-orgs/commercial-paper-network/crypto-config/peerOrganizations/digibank.example.com/peers/peer5.digibank.example.com/msp/tlscacerts/tlsca.digibank.example.com-cert.pem


# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  camagnetocorp:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false

    tlsCACerts:
      path: /home/matthew/github.com/ampretia/fabric-application-examples/infrastructure/two-orgs/commercial-paper-network/crypto-config/peerOrganizations/magnetocorp.example.com/ca/ca.magnetocorp.example.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
        enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: camagnetocorp

  cadigibank:
    url: https://localhost:8054
    tlsCACerts:
      path: /home/matthew/github.com/ampretia/fabric-application-examples/infrastructure/two-orgs/commercial-paper-network/crypto-config/peerOrganizations/digibank.example.com/ca/ca.digibank.example.com-cert.pem

    httpOptions:
      verify: false
    registrar:
        enrollId: admin
        enrollSecret: adminpw
    caName: cadigibank
